name: GuoCe
description: ''
dependencies:
  # dake: any
  browser: any
  sass: any
  # polymer: any
  # fishbone: any
  fishbone:
    path: /Users/nami/workspace/fishbone
transformers:
  - sass
  - fishbone
